# Generated by Django 4.2.1 on 2023-05-31 22:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='Имя')),
                ('token', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Токен пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audio', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['wav'])], verbose_name='Aудио')),
                ('audio_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Токен аудио')),
                ('person', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to='index.person', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Аудиозапись',
                'verbose_name_plural': 'Аудиозаписи',
            },
        ),
    ]
