# Generated by Django 4.2.1 on 2023-05-31 11:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Имя')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Токен пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audio/%Y/%m/%d/', verbose_name='Aудио')),
                ('audio_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Токен аудио')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='index.person', verbose_name='ID пользователя')),
            ],
        ),
    ]
