# Generated by Django 4.2.1 on 2023-05-31 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='person_id',
            new_name='person',
        ),
    ]
